#ifndef svn_info_h
#define svn_info_h

namespace G3D {
    /** \brief Compile-time SVN revision of G3D. 
       Used by G3D::ScreenshotDialog. Autogenerated during the G3D build.*/
    extern const int SVN_REVISION_NUMBER;
}

#endif
